interface Env {
  DB: D1Database;
  API_KEY_PEPPER: string;
  GOOGLE_CLIENT_ID: string;
}

type GoogleClaims={iss?:string;aud?:string;email?:string;email_verified?:boolean;exp?:number};
type GoogleJwk=JsonWebKey & {kid?:string;alg?:string};
type Plan={tier:string;rate_limit_per_minute:number;max_results:number};
type Customer={id:string;name:string;email:string|null;tier:string;rate_limit_per_minute:number;active:number};
const json=(body:unknown,status=200,headers:HeadersInit={})=>new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json; charset=utf-8",...headers}});
const nowIso=()=>new Date().toISOString();
const requestId=()=>`req_${crypto.randomUUID().replaceAll("-","")}`;
const b64dec=(v:string)=>{const n=v.replace(/-/g,"+").replace(/_/g,"/")+"===".slice((v.length+3)%4),b=atob(n),o=new Uint8Array(b.length);for(let i=0;i<b.length;i++)o[i]=b.charCodeAt(i);return o;};
const b64enc=(bytes:Uint8Array)=>{let s="";for(const b of bytes)s+=String.fromCharCode(b);return btoa(s).replaceAll("+","-").replaceAll("/","_").replaceAll("=","");};
const ab=(bytes:Uint8Array)=>{const copy=new Uint8Array(bytes.byteLength);copy.set(bytes);return copy.buffer;};
const error=(code:string,message:string,id:string,status:number)=>json({error:{code,message,request_id:id}},status,{"x-request-id":id});
async function importJwk(j:JsonWebKey){return crypto.subtle.importKey("jwk",j,{name:"RSASSA-PKCS1-v1_5",hash:"SHA-256"},false,["verify"]);}
let jwks:{keys:GoogleJwk[];expiresAt:number}|null=null;
async function googleKeys(){if(jwks&&jwks.expiresAt>Date.now())return jwks.keys;const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),5000);try{const r=await fetch("https://www.googleapis.com/oauth2/v3/certs",{headers:{accept:"application/json"},signal:controller.signal});if(!r.ok)throw new Error("Google keys unavailable");const maxAge=Number((r.headers.get("cache-control")??"").match(/max-age=(\d+)/i)?.[1]??3600);const body=await r.json<{keys?:GoogleJwk[]}>();const keys=body.keys??[];jwks={keys,expiresAt:Date.now()+Math.min(Math.max(maxAge,300),86400)*1000};return keys;}finally{clearTimeout(timer);}}
async function verifyGoogleIdToken(token:string,clientId:string){const p=token.split(".");if(p.length!==3)throw new Error("Invalid token");const h=JSON.parse(new TextDecoder().decode(b64dec(p[0]))) as {alg?:string;kid?:string};const c=JSON.parse(new TextDecoder().decode(b64dec(p[1]))) as GoogleClaims;if(h.alg!=="RS256"||!h.kid)throw new Error("Unsupported token");if(c.iss!=="https://accounts.google.com"&&c.iss!=="accounts.google.com")throw new Error("Invalid issuer");if(c.aud!==clientId)throw new Error("Invalid audience");if(!c.email||c.email_verified!==true)throw new Error("Email not verified");if(!c.exp||c.exp<=Math.floor(Date.now()/1000))throw new Error("Token expired");let keys=await googleKeys(),key=keys.find(k=>k.kid===h.kid);if(!key){jwks=null;keys=await googleKeys();key=keys.find(k=>k.kid===h.kid);}if(!key)throw new Error("Signing key not found");const ok=await crypto.subtle.verify("RSASSA-PKCS1-v1_5",await importJwk(key),ab(b64dec(p[2])),ab(new TextEncoder().encode(`${p[0]}.${p[1]}`)));if(!ok)throw new Error("Bad signature");return c;}
async function hashKey(key:string,pepper:string){const k=await crypto.subtle.importKey("raw",new TextEncoder().encode(pepper),{name:"HMAC",hash:"SHA-256"},false,["sign"]);return Array.from(new Uint8Array(await crypto.subtle.sign("HMAC",k,new TextEncoder().encode(key)))).map(b=>b.toString(16).padStart(2,"0")).join("");}
async function sessionToken(){const b=new Uint8Array(32);crypto.getRandomValues(b);return `mk_session_${b64enc(b)}`;}
async function issueSession(env:Env,customerId:string){const token=await sessionToken(),hash=await hashKey(token,env.API_KEY_PEPPER),now=nowIso(),expires=new Date(Date.now()+30*86400000).toISOString();await env.DB.prepare("INSERT INTO auth_sessions(session_id_hash,customer_id,expires_at,created_at,last_seen_at) VALUES(?,?,?,?,?)").bind(hash,customerId,expires,now,now).run();return token;}
async function authCustomer(env:Env,token:string){const hash=await hashKey(token,env.API_KEY_PEPPER),row=await env.DB.prepare("SELECT c.id,c.name,c.email,c.tier,c.rate_limit_per_minute,c.active FROM auth_sessions s JOIN customers c ON c.id=s.customer_id WHERE s.session_id_hash=? AND s.expires_at>? LIMIT 1").bind(hash,nowIso()).first<Customer>();if(!row)return null;await env.DB.prepare("UPDATE auth_sessions SET last_seen_at=? WHERE session_id_hash=?").bind(nowIso(),hash).run();return row;}
function normalizeGmail(value:string|null|undefined){const email=String(value??"").trim().toLowerCase();return /^[^\s@]+@gmail\.com$/.test(email)?email:null;}
const AUTH_WINDOW=600,AUTH_MAX=10;
async function authKey(env:Env,request:Request){return hashKey(`auth:${(request.headers.get("cf-connecting-ip")??"unknown").trim().slice(0,120)}`,env.API_KEY_PEPPER);}
async function blocked(env:Env,request:Request){const key=await authKey(env,request),row=await env.DB.prepare("SELECT window_started_at,failures FROM auth_rate_limits WHERE key_hash=? LIMIT 1").bind(key).first<{window_started_at:number;failures:number}>();if(!row)return false;const now=Math.floor(Date.now()/1000);if(now-row.window_started_at>=AUTH_WINDOW){await env.DB.prepare("DELETE FROM auth_rate_limits WHERE key_hash=?").bind(key).run();return false;}return row.failures>=AUTH_MAX;}
async function failure(env:Env,request:Request){const key=await authKey(env,request),now=Math.floor(Date.now()/1000);await env.DB.prepare(`INSERT INTO auth_rate_limits(key_hash,window_started_at,failures,updated_at) VALUES(?,?,1,?) ON CONFLICT(key_hash) DO UPDATE SET window_started_at=CASE WHEN ?-auth_rate_limits.window_started_at>=? THEN ? ELSE auth_rate_limits.window_started_at END,failures=CASE WHEN ?-auth_rate_limits.window_started_at>=? THEN 1 ELSE MIN(auth_rate_limits.failures+1,?) END,updated_at=?`).bind(key,now,nowIso(),now,AUTH_WINDOW,now,now,AUTH_WINDOW,AUTH_MAX,nowIso()).run();}
async function clearFailure(env:Env,request:Request){await env.DB.prepare("DELETE FROM auth_rate_limits WHERE key_hash=?").bind(await authKey(env,request)).run();}
async function freePlan(env:Env){const plan=await env.DB.prepare("SELECT tier,rate_limit_per_minute,max_results FROM plans WHERE tier='free' AND active=1 LIMIT 1").first<Plan>();if(!plan)throw new Error("Free plan unavailable");return plan;}
function publicCustomer(customer:Customer){return {id:customer.id,name:"Google account",email:customer.email,tier:"free",rate_limit_per_minute:10,active:1};}
function publicPlan(_plan:Plan){return {tier:"free",rate_limit_per_minute:10,monthly_quota:100,max_results:10};}
async function signIn(request:Request,env:Env,id:string){if(await blocked(env,request))return error("AUTH_RATE_LIMITED","Too many sign-in attempts. Please try again later.",id,429);if(request.headers.get("content-type")?.split(";",1)[0].trim()!=="application/json")return error("INVALID_CONTENT_TYPE","Request body must be JSON",id,415);let body:unknown;try{body=await request.json();}catch{await failure(env,request);return error("INVALID_JSON","Request body must be JSON",id,400);}const credential=String((body as {credential?:unknown})?.credential??"").trim();if(!credential||credential.length>12000||credential.split(".").length!==3){await failure(env,request);return error("INVALID_CREDENTIAL","Google sign-in could not be verified",id,401);}let claims:GoogleClaims;try{claims=await verifyGoogleIdToken(credential,env.GOOGLE_CLIENT_ID);}catch{await failure(env,request);return error("INVALID_GOOGLE_CREDENTIAL","Google sign-in could not be verified",id,401);}await clearFailure(env,request);const email=normalizeGmail(claims.email);if(!email)return error("GMAIL_ONLY","Please sign in with a Gmail account (@gmail.com).",id,403);await env.DB.prepare("INSERT OR IGNORE INTO google_free_accounts(email) VALUES(?)").bind(email).run();const plan=await freePlan(env);let customer=await env.DB.prepare("SELECT id,name,email,tier,rate_limit_per_minute,active FROM customers WHERE lower(email)=? LIMIT 1").bind(email).first<Customer>();if(customer){await env.DB.prepare("UPDATE customers SET name='Google account',google_sub=NULL,tier='free',monthly_quota=100,rate_limit_per_minute=?,active=1 WHERE id=?").bind(10,customer.id).run();customer={...customer,name:"Google account",email,tier:"free",rate_limit_per_minute:10,active:1};}else{const customerId=`cus_${crypto.randomUUID().replaceAll("-","")}`,created=nowIso();await env.DB.prepare("INSERT INTO customers(id,name,email,google_sub,tier,monthly_quota,rate_limit_per_minute,usage_month,monthly_usage,active,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)").bind(customerId,"Google account",email,null,"free",100,10,new Date().toISOString().slice(0,7),0,1,created).run();customer={id:customerId,name:"Google account",email,tier:"free",rate_limit_per_minute:10,active:1};}return json({customer:publicCustomer(customer),plan:publicPlan(plan),session_token:await issueSession(env,customer.id)},200,{"x-request-id":id,"cache-control":"no-store"});}
async function me(request:Request,env:Env,id:string){const token=request.headers.get("authorization")?.replace(/^Bearer\s+/i,"").trim();if(!token||token.length>256)return error("UNAUTHORIZED","Valid Momentum session required",id,401);const customer=await authCustomer(env,token);if(!customer)return error("UNAUTHORIZED","Session expired or invalid",id,401);const email=normalizeGmail(customer.email);if(!email)return error("GMAIL_ONLY","Gmail account required",id,403);await env.DB.prepare("INSERT OR IGNORE INTO google_free_accounts(email) VALUES(?)").bind(email).run();const plan=await freePlan(env);await env.DB.prepare("UPDATE customers SET name='Google account',google_sub=NULL,tier='free',monthly_quota=100,rate_limit_per_minute=?,active=1 WHERE id=?").bind(10,customer.id).run();return json({customer:publicCustomer({...customer,email,tier:"free",rate_limit_per_minute:10}),plan:publicPlan(plan)},200,{"x-request-id":id,"cache-control":"no-store"});}
async function logout(request:Request,env:Env,id:string){const token=request.headers.get("authorization")?.replace(/^Bearer\s+/i,"").trim();if(token&&token.length<=256){const hash=await hashKey(token,env.API_KEY_PEPPER);await env.DB.prepare("DELETE FROM auth_sessions WHERE session_id_hash=?").bind(hash).run();}return json({status:"signed_out"},200,{"x-request-id":id,"cache-control":"no-store"});}
export default{async fetch(request:Request,env:Env){const id=requestId(),u=new URL(request.url);if(request.method==="OPTIONS")return new Response(null,{status:204,headers:{"access-control-allow-origin":"https://therandomhuman-hub.github.io","access-control-allow-methods":"GET,POST,OPTIONS","access-control-allow-headers":"content-type,authorization,x-api-key"}});if((u.pathname==="/health"||u.pathname==="/auth/health")&&request.method==="GET"){const ready=Boolean(env.API_KEY_PEPPER&&env.GOOGLE_CLIENT_ID);return json({status:ready?"ok":"degraded",service:"momentum-auth",mode:"gmail-free"},ready?200:503,{"x-request-id":id});}if(u.pathname==="/auth/config"&&request.method==="GET")return json({google_client_id:env.GOOGLE_CLIENT_ID},200,{"x-request-id":id,"cache-control":"public,max-age=300"});if(u.pathname==="/auth/google"&&request.method==="POST")return signIn(request,env,id);if(u.pathname==="/auth/me"&&request.method==="GET")return me(request,env,id);if(u.pathname==="/auth/logout"&&request.method==="POST")return logout(request,env,id);return error("NOT_FOUND","Route not found",id,404);},async scheduled(_controller:ScheduledController,env:Env){const expired=await env.DB.prepare("SELECT session_id_hash FROM auth_sessions WHERE expires_at<=?").bind(nowIso()).all<{session_id_hash:string}>();if(expired.results?.length){for(let i=0;i<expired.results.length;i+=50){const batch=expired.results.slice(i,i+50);await env.DB.batch(batch.map(r=>env.DB.prepare("DELETE FROM auth_sessions WHERE session_id_hash=?").bind(r.session_id_hash)));}}await env.DB.prepare("DELETE FROM auth_rate_limits WHERE updated_at<?").bind(new Date(Date.now()-86400000).toISOString()).run();}};
