interface Env {
  DB: D1Database;
  API_KEY_PEPPER: string;
  GOOGLE_CLIENT_ID: string;
  ADMIN_SECRET?: string;
}

type GoogleClaims = { iss?: string; aud?: string; sub?: string; email?: string; email_verified?: boolean; exp?: number };
type GoogleJwk = JsonWebKey & { kid?: string; alg?: string; use?: string };
type Plan = { tier: string; monthly_quota: number; rate_limit_per_minute: number; max_results: number };
type Customer = { id: string; name: string; email: string | null; tier: string; monthly_quota: number; rate_limit_per_minute: number; active: number };

const json=(body:unknown,status=200,headers:HeadersInit={})=>new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json; charset=utf-8",...headers}});
const nowIso=()=>new Date().toISOString();
const monthKey=()=>new Date().toISOString().slice(0,7);
const requestId=()=>`req_${crypto.randomUUID().replaceAll("-","")}`;
function error(code:string,message:string,id:string,status:number){return json({error:{code,message,request_id:id}},status,{"x-request-id":id});}
function b64dec(value:string):Uint8Array{const normalized=value.replace(/-/g,"+").replace(/_/g,"/")+"===".slice((value.length+3)%4);const binary=atob(normalized);const out=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)out[i]=binary.charCodeAt(i);return out;}
function b64enc(bytes:Uint8Array):string{let s="";for(const b of bytes)s+=String.fromCharCode(b);return btoa(s).replaceAll("+","-").replaceAll("/","_").replaceAll("=","");}
function asArrayBuffer(bytes:Uint8Array):ArrayBuffer{const copy=new Uint8Array(bytes.byteLength);copy.set(bytes);return copy.buffer;}
async function importJwk(jwk:JsonWebKey):Promise<CryptoKey>{return crypto.subtle.importKey("jwk",jwk,{name:"RSASSA-PKCS1-v1_5",hash:"SHA-256"},false,["verify"]);}
let jwksCache:{keys:GoogleJwk[];expiresAt:number}|null=null;
async function googleKeys():Promise<GoogleJwk[]>{if(jwksCache&&jwksCache.expiresAt>Date.now())return jwksCache.keys;const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),5000);try{const r=await fetch("https://www.googleapis.com/oauth2/v3/certs",{headers:{accept:"application/json"},signal:controller.signal});if(!r.ok)throw new Error("Google signing keys unavailable");const cc=r.headers.get("cache-control")??"";const maxAge=Number(cc.match(/max-age=(\d+)/i)?.[1]??3600);const body=await r.json<{keys?:GoogleJwk[]}>();const keys=body.keys??[];jwksCache={keys,expiresAt:Date.now()+Math.min(Math.max(maxAge,300),86400)*1000};return keys;}finally{clearTimeout(timer);}}
async function verifyGoogleIdToken(token:string,clientId:string):Promise<GoogleClaims>{const p=token.split(".");if(p.length!==3)throw new Error("Invalid Google ID token");const header=JSON.parse(new TextDecoder().decode(b64dec(p[0]))) as {alg?:string;kid?:string};const claims=JSON.parse(new TextDecoder().decode(b64dec(p[1]))) as GoogleClaims;if(header.alg!=="RS256"||!header.kid)throw new Error("Unsupported Google ID token");if(claims.iss!=="https://accounts.google.com"&&claims.iss!=="accounts.google.com")throw new Error("Invalid Google token issuer");if(claims.aud!==clientId)throw new Error("Google token audience mismatch");if(!claims.email||claims.email_verified!==true)throw new Error("Google email is not verified");if(!claims.exp||claims.exp<=Math.floor(Date.now()/1000))throw new Error("Google ID token expired");let keys=await googleKeys();let jwk=keys.find(k=>k.kid===header.kid);if(!jwk){jwksCache=null;keys=await googleKeys();jwk=keys.find(k=>k.kid===header.kid);}if(!jwk)throw new Error("Google signing key not found");const valid=await crypto.subtle.verify("RSASSA-PKCS1-v1_5",await importJwk(jwk),asArrayBuffer(b64dec(p[2])),asArrayBuffer(new TextEncoder().encode(`${p[0]}.${p[1]}`)));if(!valid)throw new Error("Invalid Google ID token signature");return claims;}
async function hashKey(key:string,pepper:string):Promise<string>{const k=await crypto.subtle.importKey("raw",new TextEncoder().encode(pepper),{name:"HMAC",hash:"SHA-256"},false,["sign"]);return Array.from(new Uint8Array(await crypto.subtle.sign("HMAC",k,new TextEncoder().encode(key)))).map(b=>b.toString(16).padStart(2,"0")).join("");}
async function generateSessionToken():Promise<string>{const b=new Uint8Array(32);crypto.getRandomValues(b);return `mk_session_${b64enc(b)}`;}
async function issueSession(env:Env,customerId:string):Promise<string>{const token=await generateSessionToken();const hash=await hashKey(token,env.API_KEY_PEPPER);const now=nowIso();const expires=new Date(Date.now()+30*86400000).toISOString();await env.DB.batch([env.DB.prepare(`INSERT INTO auth_sessions(session_id_hash,customer_id,expires_at,created_at,last_seen_at) VALUES(?,?,?,?,?)`).bind(hash,customerId,expires,now,now),env.DB.prepare(`INSERT INTO api_keys(id,customer_id,key_prefix,key_hash,active,created_at) VALUES(?,?,?,?,?,?)`).bind(`sess_${crypto.randomUUID().replaceAll("-","")}`,customerId,token.slice(0,16),hash,1,now)]);return token;}
async function authenticateSession(env:Env,token:string):Promise<Customer|null>{const hash=await hashKey(token,env.API_KEY_PEPPER);const row=await env.DB.prepare(`SELECT c.id,c.name,c.email,c.tier,c.monthly_quota,c.rate_limit_per_minute,c.active FROM auth_sessions s JOIN customers c ON c.id=s.customer_id WHERE s.session_id_hash=? AND s.expires_at>? LIMIT 1`).bind(hash,nowIso()).first<Customer>();if(!row)return null;await env.DB.prepare("UPDATE auth_sessions SET last_seen_at=? WHERE session_id_hash=?").bind(nowIso(),hash).run();return row;}

const AUTH_WINDOW_SECONDS=600;
const AUTH_MAX_FAILURES=10;
async function authThrottleKey(env:Env,request:Request):Promise<string>{const ip=(request.headers.get("cf-connecting-ip")??"unknown").trim().slice(0,120);return hashKey(`auth:${ip}`,env.API_KEY_PEPPER);}
async function authBlocked(env:Env,request:Request):Promise<boolean>{const key=await authThrottleKey(env,request);const row=await env.DB.prepare("SELECT window_started_at,failures FROM auth_rate_limits WHERE key_hash=? LIMIT 1").bind(key).first<{window_started_at:number;failures:number}>();if(!row)return false;const now=Math.floor(Date.now()/1000);if(now-row.window_started_at>=AUTH_WINDOW_SECONDS){await env.DB.prepare("DELETE FROM auth_rate_limits WHERE key_hash=?").bind(key).run();return false;}return row.failures>=AUTH_MAX_FAILURES;}
async function authRecordFailure(env:Env,request:Request):Promise<void>{const key=await authThrottleKey(env,request);const now=Math.floor(Date.now()/1000);await env.DB.prepare(`INSERT INTO auth_rate_limits(key_hash,window_started_at,failures,updated_at) VALUES(?,?,1,?) ON CONFLICT(key_hash) DO UPDATE SET window_started_at=CASE WHEN ?-auth_rate_limits.window_started_at>=? THEN ? ELSE auth_rate_limits.window_started_at END,failures=CASE WHEN ?-auth_rate_limits.window_started_at>=? THEN 1 ELSE MIN(auth_rate_limits.failures+1,?) END,updated_at=?`).bind(key,now,nowIso(),now,AUTH_WINDOW_SECONDS,now,now,AUTH_WINDOW_SECONDS,AUTH_MAX_FAILURES,nowIso()).run();}
async function authClearFailures(env:Env,request:Request):Promise<void>{const key=await authThrottleKey(env,request);await env.DB.prepare("DELETE FROM auth_rate_limits WHERE key_hash=?").bind(key).run();}
function normalizeGmail(value:string|undefined|null):string|null{const email=String(value??"").trim().toLowerCase();return /^[^\s@]+@gmail\.com$/.test(email)?email:null;}
async function getAccessTier(env:Env,email:string):Promise<"free"|"pro">{const row=await env.DB.prepare("SELECT email FROM google_pro_accounts WHERE email=? LIMIT 1").bind(email).first<{email:string}>();return row?"pro":"free";}
async function syncCustomerTier(env:Env,customerId:string,tier:"free"|"pro"){const plan=await env.DB.prepare("SELECT tier,monthly_quota,rate_limit_per_minute FROM plans WHERE tier=? AND active=1 LIMIT 1").bind(tier).first<Plan>();if(!plan)throw new Error(`${tier} plan unavailable`);await env.DB.prepare("UPDATE customers SET name='Google account',google_sub=NULL,tier=?,monthly_quota=?,rate_limit_per_minute=?,active=1 WHERE id=?").bind(tier,plan.monthly_quota,plan.rate_limit_per_minute,customerId).run();return plan;}
async function ensureFreeList(env:Env,email:string,tier:"free"|"pro"){if(tier==="pro"){await env.DB.prepare("DELETE FROM google_free_accounts WHERE email=?").bind(email).run();return;}await env.DB.prepare("INSERT OR IGNORE INTO google_free_accounts(email) VALUES(?)").bind(email).run();}

async function googleSignIn(request:Request,env:Env,id:string):Promise<Response>{if(await authBlocked(env,request))return error("AUTH_RATE_LIMITED","Too many sign-in attempts. Please try again later.",id,429);if(request.headers.get("content-type")?.split(";",1)[0].trim()!=="application/json")return error("INVALID_CONTENT_TYPE","Request body must be JSON",id,415);const length=Number(request.headers.get("content-length")??0);if(length>16384)return error("REQUEST_TOO_LARGE","Request body is too large",id,413);let body:unknown;try{body=await request.json();}catch{await authRecordFailure(env,request);return error("INVALID_JSON","Request body must be JSON",id,400);}const credential=String((body as {credential?:unknown})?.credential??"").trim();if(!credential||credential.length>12000||credential.split(".").length!==3){await authRecordFailure(env,request);return error("INVALID_CREDENTIAL","Google sign-in could not be verified",id,401);}let claims:GoogleClaims;try{claims=await verifyGoogleIdToken(credential,env.GOOGLE_CLIENT_ID);}catch{await authRecordFailure(env,request);return error("INVALID_GOOGLE_CREDENTIAL","Google sign-in could not be verified",id,401);}await authClearFailures(env,request);const email=normalizeGmail(claims.email);if(!email)return error("GMAIL_ONLY","Please sign in with a Gmail account (@gmail.com).",id,403);const tier=await getAccessTier(env,email);await ensureFreeList(env,email,tier);let customer=await env.DB.prepare("SELECT id,name,email,tier,monthly_quota,rate_limit_per_minute,active FROM customers WHERE lower(email)=? LIMIT 1").bind(email).first<Customer>();let plan:Plan;if(customer){plan=await syncCustomerTier(env,customer.id,tier);customer={...customer,name:"Google account",email,tier,monthly_quota:plan.monthly_quota,rate_limit_per_minute:plan.rate_limit_per_minute,active:1};}else{plan=await env.DB.prepare("SELECT tier,monthly_quota,rate_limit_per_minute,max_results FROM plans WHERE tier=? AND active=1 LIMIT 1").bind(tier).first<Plan>() as Plan;if(!plan)return error("PLAN_UNAVAILABLE",`${tier} plan is not configured`,id,503);const customerId=`cus_${crypto.randomUUID().replaceAll("-","")}`;const created=nowIso();await env.DB.prepare(`INSERT INTO customers(id,name,email,google_sub,tier,monthly_quota,rate_limit_per_minute,usage_month,monthly_usage,active,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)`).bind(customerId,"Google account",email,null,tier,plan.monthly_quota,plan.rate_limit_per_minute,monthKey(),0,1,created).run();customer={id:customerId,name:"Google account",email,tier,monthly_quota:plan.monthly_quota,rate_limit_per_minute:plan.rate_limit_per_minute,active:1};}const session=await issueSession(env,customer.id);return json({customer,plan,session_token:session},200,{"x-request-id":id,"cache-control":"no-store"});}
async function sessionMe(request:Request,env:Env,id:string):Promise<Response>{const token=request.headers.get("authorization")?.replace(/^Bearer\s+/i,"").trim();if(!token||token.length>256)return error("UNAUTHORIZED","Valid Momentum session required",id,401);const customer=await authenticateSession(env,token);if(!customer)return error("UNAUTHORIZED","Session expired or invalid",id,401);const email=normalizeGmail(customer.email);if(!email)return error("GMAIL_ONLY","Gmail account required",id,403);const tier=await getAccessTier(env,email);const plan=await syncCustomerTier(env,customer.id,tier);return json({customer:{...customer,name:"Google account",email,tier,monthly_quota:plan.monthly_quota,rate_limit_per_minute:plan.rate_limit_per_minute,active:1},plan},200,{"x-request-id":id,"cache-control":"no-store"});}
async function adminAccess(request:Request,env:Env,id:string):Promise<Response>{const supplied=request.headers.get("x-admin-secret")??"";if(!env.ADMIN_SECRET||supplied!==env.ADMIN_SECRET)return error("FORBIDDEN","Invalid admin credential",id,403);if(request.headers.get("content-type")?.split(";",1)[0].trim()!=="application/json")return error("INVALID_CONTENT_TYPE","Request body must be JSON",id,415);let body:unknown;try{body=await request.json();}catch{return error("INVALID_JSON","Request body must be JSON",id,400);}const email=normalizeGmail(String((body as {email?:unknown})?.email??""));if(!email)return error("INVALID_GMAIL","A valid @gmail.com address is required",id,400);const action=request.url.endsWith("/grant")?"grant":"revoke";if(action==="grant"){await env.DB.batch([env.DB.prepare("INSERT OR IGNORE INTO google_pro_accounts(email) VALUES(?)").bind(email),env.DB.prepare("DELETE FROM google_free_accounts WHERE email=?").bind(email)]);const customer=await env.DB.prepare("SELECT id FROM customers WHERE lower(email)=? LIMIT 1").bind(email).first<{id:string}>();if(customer)await syncCustomerTier(env,customer.id,"pro");}else{await env.DB.batch([env.DB.prepare("DELETE FROM google_pro_accounts WHERE email=?").bind(email),env.DB.prepare("INSERT OR IGNORE INTO google_free_accounts(email) VALUES(?)").bind(email)]);const customer=await env.DB.prepare("SELECT id FROM customers WHERE lower(email)=? LIMIT 1").bind(email).first<{id:string}>();if(customer)await syncCustomerTier(env,customer.id,"free");}return json({status:action,email,tier:action==="grant"?"pro":"free"},200,{"x-request-id":id,"cache-control":"no-store"});}
async function logout(request:Request,env:Env,id:string):Promise<Response>{const token=request.headers.get("authorization")?.replace(/^Bearer\s+/i,"").trim();if(token&&token.length<=256){const hash=await hashKey(token,env.API_KEY_PEPPER);await env.DB.batch([env.DB.prepare("DELETE FROM auth_sessions WHERE session_id_hash=?").bind(hash),env.DB.prepare("UPDATE api_keys SET active=0 WHERE key_hash=? AND substr(key_prefix,1,11)='mk_session_'").bind(hash)]);}return json({status:"signed_out"},200,{"x-request-id":id,"cache-control":"no-store"});}

export default{async fetch(request:Request,env:Env){const id=requestId(),u=new URL(request.url);if(request.method==="OPTIONS")return new Response(null,{status:204,headers:{"access-control-allow-origin":"https://therandomhuman-hub.github.io","access-control-allow-methods":"GET,POST,OPTIONS","access-control-allow-headers":"content-type,authorization,x-admin-secret"}});if(u.pathname==="/health"&&request.method==="GET")return json({status:"ok",service:"momentum-auth",mode:"gmail-access"},200,{"x-request-id":id});if(u.pathname==="/auth/config"&&request.method==="GET")return json({google_client_id:env.GOOGLE_CLIENT_ID},200,{"x-request-id":id,"cache-control":"public,max-age=300"});if(u.pathname==="/auth/google"&&request.method==="POST")return googleSignIn(request,env,id);if(u.pathname==="/auth/me"&&request.method==="GET")return sessionMe(request,env,id);if(u.pathname==="/auth/logout"&&request.method==="POST")return logout(request,env,id);if(u.pathname==="/admin/pro/grant"&&request.method==="POST")return adminAccess(request,env,id);if(u.pathname==="/admin/pro/revoke"&&request.method==="POST")return adminAccess(request,env,id);return error("NOT_FOUND","Route not found",id,404);},async scheduled(_controller:ScheduledController,env:Env){const now=nowIso();const expired=await env.DB.prepare("SELECT session_id_hash FROM auth_sessions WHERE expires_at<=?").bind(now).all<{session_id_hash:string}>();if(expired.results?.length){for(let i=0;i<expired.results.length;i+=50){const batch=expired.results.slice(i,i+50);await env.DB.batch(batch.map(r=>env.DB.prepare("UPDATE api_keys SET active=0 WHERE key_hash=? AND substr(key_prefix,1,11)='mk_session_'").bind(r.session_id_hash)));}await env.DB.prepare("DELETE FROM auth_sessions WHERE expires_at<=?").bind(now).run();}await env.DB.prepare("DELETE FROM auth_rate_limits WHERE updated_at<?").bind(new Date(Date.now()-86400000).toISOString()).run();}};
